-- # Created At: 03-06-2025
-- # Description: Insert queries for ChartsSourceOfTruth radiology elements
-- # Related to: EN-2749

-- FRACTURE ITEMS (F001-F022)
INSERT INTO public."ChartsSourceOfTruth" (
    "Id", "ChartCode", "ChartSectionId", "ChartType", "AnswerCode", 
    "Label", "Value", "Type", "CreatedAt", "CreatedBy", "UpdatedAt", 
    "UpdatedBy", "Deleted", "DeletedAt", "DeletedBy"
) VALUES 
-- F001 - Ankle
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F001Q001A001', 'Ankle', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F001Q001A002', 'Left', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F001Q001A003', 'Right', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F001Q001A004', 'Lateral Malleolus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F001Q001A005', 'Medial Malleolus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F001Q001A006', 'Bimalleolar', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F001Q001A007', 'Trimalleolar', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F001Q001A008', 'Distal Tibial Pilon', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F001Q001A009', 'SH', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F001Q001A010', 'SH Type 1', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F001Q001A011', 'SH Type 2', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F001Q001A012', 'SH Type 3', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F001Q001A013', 'SH Type 4', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F001Q001A014', 'SH Type 5', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F001Q001A016', 'Nondisplaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F001Q001A017', 'Displaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F002 - C1
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F002Q001A001', 'C1 Fracture', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F002Q001A002', 'Arch', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F002Q001A003', 'Anterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F002Q001A004', 'Posterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F002Q001A005', 'Burst (Jefferson Fracture)', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F002Q001A006', 'Lateral Mass', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F002Q001A007', 'Stable', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F002Q001A008', 'Unstable', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F002Q001A009', 'Nondisplaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F002Q001A010', 'Displaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F003 - C2
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F003Q001A001', 'C2 Fracture', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F003Q001A002', 'Dens', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F003Q001A003', 'Dens Type I', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F003Q001A004', 'Dens Type II', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F003Q001A005', 'Dens Type III', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F003Q001A006', 'Extension Teardrop', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F003Q001A008', 'Traumatic Spondylolisthesis (Hangman''s Fracture)', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F003Q001A009', 'Hangman''s Type I', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F003Q001A010', 'Hangman''s Type II', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F003Q001A011', 'Hangman''s Type IIA', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F003Q001A012', 'Hangman''s Type III', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F003Q001A014', 'Stable', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F003Q001A015', 'Unstable', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F003Q001A016', 'Nondisplaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F003Q001A017', 'Displaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F004 - CTLS
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F004Q001A001', 'Cervical', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F004Q001A002', 'Thoracic', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F004Q001A003', 'Lumbar', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F004Q001A004', 'Sacral', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F004Q001A005', 'Level', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F004Q001A007', 'Wedge', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F004Q001A008', 'Teardrop', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F004Q001A009', 'Burst', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F004Q001A010', 'Spinous Process', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F004Q001A011', 'Stable', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F004Q001A012', 'Unstable', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F004Q001A013', 'Nondisplaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F004Q001A014', 'Displaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F006 - Clavicle
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F006Q001A001', 'Clavicle', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F006Q001A002', 'Left', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F006Q001A003', 'Right', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F006Q001A004', 'Proximal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F006Q001A005', 'Shaft', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F006Q001A006', 'Distal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F006Q001A007', 'Nondisplaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F006Q001A008', 'Displaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F006Q001A009', 'Anterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F006Q001A010', 'Middle', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F006Q001A011', 'Posterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F007 - Facial
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A001', 'Facial', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A002', 'Left', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A003', 'Right', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A004', 'Nasal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A005', 'Orbit', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A006', 'Malar', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A007', 'Maxilla', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A008', 'Zygoma', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A009', 'Le Fort', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A010', 'Le Fort I', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A011', 'Le Fort II', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A012', 'Le Fort III', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A014', 'Mandible', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A015', 'Mandible Ramus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A016', 'Mandible Angle', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A017', 'Mandible Body', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A018', 'Mandible Condyle', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A019', 'Mandible Subcondyle', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F007Q001A020', 'Mandible Symphysis', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F008 - Femur
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A001', 'Femur', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A002', 'Left', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A003', 'Right', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A004', 'Head', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A005', 'Head Articular Surface', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A006', 'Neck', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A007', 'Subcapital', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A008', 'Transcervical', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A009', 'Base', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A010', 'Intertrochanteric', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A011', 'Greater Trochanter', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A012', 'Lesser Trochanter', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A013', 'Subtrochanteric', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A015', 'Shaft', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A016', 'Shaft Transverse', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A017', 'Shaft Oblique', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A018', 'Shaft Spiral', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A019', 'Shaft Segmental', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A020', 'Shaft Comminuted', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A022', 'Distal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A023', 'Supracondylar', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A024', 'Supracondylar with Intercondylar', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A025', 'SH', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A026', 'SH Type 1', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A027', 'SH Type 2', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A028', 'SH Type 3', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A029', 'SH Type 4', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A030', 'SH Type 5', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A032', 'Condyle', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A033', 'Medial Condyle', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F008Q001A034', 'Lateral Condyle', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F009 - Fibula
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A001', 'Fibula', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A002', 'Left', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A003', 'Right', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A004', 'Proximal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A005', 'Proximal Linear', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A006', 'Proximal Avulsion', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A007', 'Proximal Stress', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A008', 'Proximal Maisonneuve', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A009', 'Proximal Torus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A010', 'Proximal SH', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A011', 'Proximal SH Type 1', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A012', 'Proximal SH Type 2', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A013', 'Proximal SH Type 3', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A014', 'Proximal SH Type 4', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A015', 'Proximal SH Type 5', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A017', 'Shaft', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A018', 'Shaft Transverse', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A019', 'Shaft Oblique', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A020', 'Shaft Spiral', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A021', 'Shaft Segmental', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A022', 'Shaft Comminuted', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A024', 'Distal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A025', 'Distal Lateral Malleolus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A026', 'Distal Comminuted', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A027', 'Distal Torus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A028', 'Distal SH', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A029', 'Distal SH Type 1', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A030', 'Distal SH Type 2', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A031', 'Distal SH Type 3', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A032', 'Distal SH Type 4', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F009Q001A033', 'Distal SH Type 5', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F010 - Foot
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A001', 'Foot', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A002', 'Left', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A003', 'Right', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A004', 'Calcaneus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A005', 'Calcaneus Body', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A006', 'Calcaneus Anterior Process', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A007', 'Calcaneus Tuberosity', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A008', 'Calcaneus Extra-articular', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A009', 'Calcaneus Intra-articular', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A011', 'Talus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A012', 'Talus Head', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A013', 'Talus Neck', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A014', 'Talus Body', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A015', 'Talus Dome', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A016', 'Talus Posterior Process', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A017', 'Talus Lateral Process', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A018', 'Talus Extra-articular', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A019', 'Talus Intra-articular', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A020', 'Talus Avulsion', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A021', 'Talus Chip Fracture', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A023', 'Navicular', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A024', 'Cuboid', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A025', 'Cuneiform', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A026', 'Medial Cuneiform', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A027', 'Middle Cuneiform', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A028', 'Lateral Cuneiform', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A030', 'Metatarsal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A031', '1st Metatarsal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A032', '2nd Metatarsal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F010Q001A033', '3rd Metatarsal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F011 - Metacarpal
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A001', 'Metacarpal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A002', 'Left', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A003', 'Right', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A004', '1st Metacarpal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A005', '2nd Metacarpal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A006', '3rd Metacarpal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A007', '4th Metacarpal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A008', '5th Metacarpal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A009', 'Base', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A010', 'Shaft', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A011', 'Neck', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A012', 'Head', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A013', 'Bennett''s', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A014', 'Rolando''s', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A015', 'SH', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A016', 'SH Type 1', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A017', 'SH Type 2', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A018', 'SH Type 3', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A019', 'SH Type 4', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A020', 'SH Type 5', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A022', 'Nondisplaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F011Q001A023', 'Displaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F012 - Patella
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F012Q001A001', 'Patella', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F012Q001A002', 'Left', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F012Q001A003', 'Right', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F012Q001A004', 'Longitudinal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F012Q001A005', 'Transverse', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F012Q001A006', 'Comminuted', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F012Q001A007', 'Osteochondral', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F012Q001A009', 'Nondisplaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F012Q001A010', 'Displaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F013 - Pelvic
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A001', 'Pelvic', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A002', 'Pubic', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A003', 'Left Pubic', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A004', 'Right Pubic', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A005', 'Pubic Superior Ramus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A006', 'Pubic Inferior Ramus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A008', 'Ischium', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A009', 'Left Ischium', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A010', 'Right Ischium', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A011', 'Ischium Avulsion', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A012', 'Ischium Ramus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A013', 'Ischium Tuberosity', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A014', 'Ischium Displaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A016', 'Acetabulum', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A017', 'Left Acetabulum', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A018', 'Right Acetabulum', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A019', 'Acetabulum Anterior Wall', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A020', 'Acetabulum Medial', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A021', 'Acetabulum Posterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A022', 'Acetabulum Dome', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A023', 'Acetabulum Displaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A025', 'Ilium', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A026', 'Left Ilium', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A027', 'Right Ilium', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A028', 'Ilium Wing', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A029', 'Ilium Anterior Superior Spine', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A030', 'Ilium Anterior Inferior Spine', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A031', 'Ilium Avulsion', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A032', 'Ilium Comminuted', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A033', 'Ilium Linear', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F013Q001A034', 'Ilium Displaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F014 - Phalanx
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A001', 'Phalanx', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A002', 'Left', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A003', 'Right', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A004', '1st Phalanx', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A005', '2nd Phalanx', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A006', '3rd Phalanx', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A007', '4th Phalanx', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A008', '5th Phalanx', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A009', 'Lateral Malleolus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A010', 'Medial Malleolus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A011', 'Bimalleolar', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A012', 'SH', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A013', 'SH Type 1', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A014', 'SH Type 2', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A015', 'SH Type 3', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A016', 'SH Type 4', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A017', 'SH Type 5', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A019', 'Nondisplaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F014Q001A020', 'Displaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F015 - Radius
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A001', 'Radius', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A002', 'Left', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A003', 'Right', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A004', 'Proximal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A005', 'Proximal Head', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A006', 'Proximal Neck', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A007', 'Proximal Torus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A008', 'Proximal SH', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A009', 'Proximal SH Type 1', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A010', 'Proximal SH Type 2', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A011', 'Proximal SH Type 3', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A012', 'Proximal SH Type 4', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A013', 'Proximal SH Type 5', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A015', 'Shaft', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A016', 'Shaft Transverse', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A017', 'Shaft Oblique', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A018', 'Shaft Spiral', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A019', 'Shaft Segmental', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A020', 'Shaft Comminuted', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A021', 'Galeazzi\'s', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A022', 'Greenstick', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A023', 'Bent Bone', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A025', 'Distal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A026', 'Colles\'s', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A027', 'Smith\'s', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A028', 'Barton\'s', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A029', 'Distal Intra-articular', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A030', 'Distal Torus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A031', 'Distal Styloid', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A032', 'Distal SH', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A033', 'Distal SH Type 1', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A034', 'Distal SH Type 2', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F015Q001A035', 'Distal SH Type 3', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F016 - Sacrum
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F016Q001A001', 'Sacrum', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F016Q001A002', 'Transverse', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F016Q001A003', 'Transverse Displaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F016Q001A004', 'Transverse Anterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F016Q001A005', 'Transverse Posterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F016Q001A006', 'Upper Comminuted', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F016Q001A008', 'Vertical Fracture Through', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F016Q001A009', 'Vertical Through Ala', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F016Q001A010', 'Vertical Through Foramen', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F016Q001A011', 'Vertical Through Spinal Canal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F016Q001A012', 'Vertical Displaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F016Q001A013', 'Vertical Mild Displacement', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F016Q001A014', 'Vertical Galeazzi\'s', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F016Q001A015', 'Vertical Severe Displacement', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F017 - Scapula
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F017Q001A001', 'Scapula', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F017Q001A002', 'Left', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F017Q001A003', 'Right', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F017Q001A004', 'Glenoid', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F017Q001A005', 'Neck', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F017Q001A006', 'Acromion', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F017Q001A007', 'Coracoid Process', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F017Q001A008', 'Body', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F017Q001A010', 'Nondisplaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F017Q001A011', 'Displaced', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F018 - Skull
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F018Q001A001', 'Skull', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F018Q001A002', 'Left', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F018Q001A003', 'Right', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F018Q001A004', 'Frontal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F018Q001A005', 'Parietal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F018Q001A006', 'Temporal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F018Q001A007', 'Occipital', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F018Q001A008', 'Basilar', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F018Q001A009', 'Basilar Anterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F018Q001A010', 'Basilar Middle', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F018Q001A011', 'Basilar Posterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F018Q001A013', 'Linear', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F018Q001A014', 'Comminuted', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F018Q001A015', 'Depressed', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F019 - Tibia
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A001', 'Tibia', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A002', 'Left', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A003', 'Right', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A004', 'Proximal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A005', 'Proximal Spine', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A006', 'Proximal Tuberosity', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A007', 'Proximal Condyle', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A008', 'Proximal Medial Condyle', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A009', 'Proximal Lateral Condyle', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A010', 'Proximal SH', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A011', 'Proximal SH Type 1', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A012', 'Proximal SH Type 2', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A013', 'Proximal SH Type 3', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A014', 'Proximal SH Type 4', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A015', 'Proximal SH Type 5', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A017', 'Shaft', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A018', 'Shaft Transverse', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A019', 'Shaft Oblique', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A020', 'Shaft Spiral', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A021', 'Shaft Segmental', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A022', 'Shaft Comminuted', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A024', 'Distal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A025', 'Distal Medial Malleolus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A026', 'Distal Pilon', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A027', 'Distal Torus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A028', 'Distal SH', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A029', 'Distal SH Type 1', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A030', 'Distal SH Type 2', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A031', 'Distal SH Type 3', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A032', 'Distal SH Type 4', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F019Q001A033', 'Distal SH Type 5', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- F020 - Rib
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F020Q001A001', 'Rib', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F020Q001A002', 'Left', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F020Q001A003', 'Right', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F020Q001A004', 'Single', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F020Q001A005', 'Multiple', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL)

-- F021 - Sternum
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F021Q001A001', 'Sternum', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F021Q001A002', 'Body', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F021Q001A003', 'Manubrium', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F021Q001A004', 'Xiphoid', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL)

-- F022 - Ulna
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A001', 'Ulna', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A002', 'Left', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A003', 'Right', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A004', 'Proximal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A005', 'Proximal Olecranon', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A006', 'Proximal Coronoid Process', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A007', 'Proximal Intra-articular', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A008', 'Proximal Torus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A010', 'Shaft', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A011', 'Shaft Transverse', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A012', 'Shaft Oblique', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A013', 'Shaft Spiral', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A014', 'Shaft Segmental', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A015', 'Shaft Comminuted', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A016', "Shaft Monteggia's", NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A017', 'Shaft Greenstick', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A018', 'Shaft Bent Bone', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A020', 'Distal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A021', 'Distal Styloid', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A022', 'Distal Transverse', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A023', 'Distal Oblique', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A024', 'Distal Comminuted', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'F022Q001A025', 'Distal Torus', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- D001 - Acromioclavicular
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D001Q001A001', 'AC Joint', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D001Q001A002', 'L', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D001Q001A003', 'R', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D001Q001A004', 'posterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D001Q001A005', 'inferior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D001Q001A006', 'displaced:', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D001Q001A007', '100%-200%', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D001Q001A008', '>200%', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D001Q001A009', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D001Q001A010', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- D002 - Ankle
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D002Q001A001', 'AC Joint', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D002Q001A002', 'L', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D002Q001A003', 'R', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D002Q001A004', 'subtalar', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D002Q001A005', 'midtalar', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D002Q001A006', 'transmetatarsal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D002Q001A007', 'Lisfranc', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D002Q001A008', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D002Q001A009', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- D003 - Carpal
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D003Q001A001', 'AC Joint', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D003Q001A002', 'L', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D003Q001A003', 'R', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D003Q001A004', 'lunate', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D003Q001A005', 'perilunate', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D003Q001A006', 'scapholunate', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D003Q001A007', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D003Q001A008', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),


-- D004 - Elbow
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D004Q001A001', 'AC Joint', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D004Q001A002', 'L', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D004Q001A003', 'R', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D004Q001A004', 'posterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D004Q001A005', 'anterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D004Q001A006', 'lateral', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D004Q001A007', 'medial', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D004Q001A008', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D004Q001A009', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- D005 - Finger
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D005Q001A001', 'AC Joint', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D005Q001A002', 'L', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D005Q001A003', 'R', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D005Q001A004', 'DIP', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D005Q001A005', 'PIP', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D005Q001A006', 'MCP', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D005Q001A007', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D005Q001A008', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- D006 - Hip
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D006Q001A001', 'AC Joint', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D006Q001A002', 'L', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D006Q001A003', 'R', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D006Q001A004', 'posterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D006Q001A005', 'anterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D006Q001A006', 'central', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D006Q001A007', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D006Q001A008', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL)

-- D007 - Knee
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D007Q001A001', 'AC Joint', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D007Q001A002', 'L', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D007Q001A003', 'R', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D007Q001A004', 'patella', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D007Q001A005', 'tibiofemoral', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D007Q001A006', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D007Q001A007', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- D008 - Patella
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D008Q001A001', 'AC Joint', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D008Q001A002', 'L', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D008Q001A003', 'R', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D008Q001A004', 'lateral', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D008Q001A005', 'medial', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D008Q001A006', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D008Q001A007', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- D009 - Shoulder
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D009Q001A001', 'AC Joint', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D009Q001A002', 'L', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D009Q001A003', 'R', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D009Q001A004', 'anterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D009Q001A005', 'posterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D009Q001A006', 'inferior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D009Q001A007', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D009Q001A008', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- D010 - Temporomandibular
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D010Q001A001', 'AC Joint', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D010Q001A002', 'L', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D010Q001A003', 'R', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D010Q001A004', 'anterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D010Q001A005', 'posterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D010Q001A006', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D010Q001A007', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- D011 - Toe
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D011Q001A001', 'AC Joint', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D011Q001A002', 'L', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D011Q001A003', 'R', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D011Q001A004', 'IP', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D011Q001A005', 'MTP', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D011Q001A006', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D011Q001A007', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- D012 - Wrist
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D012Q001A001', 'AC Joint', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D012Q001A002', 'L', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D012Q001A003', 'R', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D012Q001A004', 'radiocarpal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D012Q001A005', 'midcarpal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D012Q001A006', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D012Q001A007', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL)

-- D013 - Shoulder
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D013Q001A001', 'Shoulder', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D013Q001A002', 'L', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D013Q001A003', 'R', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D013Q001A004', 'anterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D013Q001A005', 'posterior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D013Q001A006', 'inferior', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D013Q001A007', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D013Q001A008', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- D014 - Toe
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D014Q001A001', 'Toe', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D014Q001A002', 'L', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D014Q001A003', 'R', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D014Q001A004', '1st', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D014Q001A005', '2nd', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D014Q001A006', '3rd', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D014Q001A007', '4th', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D014Q001A008', '5th', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D014Q001A009', 'MTP', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D014Q001A010', 'PIP', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D014Q001A011', 'IP', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D014Q001A012', 'DIP', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D014Q001A013', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D014Q001A014', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),

-- D015 - Wrist
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D015Q001A001', 'Wrist', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D015Q001A002', 'L', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D015Q001A003', 'R', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D015Q001A004', 'distal radioulnar', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D015Q001A005', 'radiocarpal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D015Q001A006', 'midcarpal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D015Q001A007', 'carpometacarpal', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D015Q001A008', '1st', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D015Q001A009', '2nd', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D015Q001A010', '3rd', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D015Q001A011', '4th', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D015Q001A012', '5th', NULL, 'cross-option', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D015Q001A013', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL),
(gen_random_uuid(), 'SHARED', 'SRAD', 'Any', 'D015Q001A014', NULL, NULL, 'input', NOW(), NULL, NOW(), NULL, false, NULL, NULL)
ON CONFLICT ("AnswerCode") DO NOTHING;