name: Post Merge Migrations

on:
  pull_request:
    types: [closed]
    paths:
      - "**/*.sql"

jobs:
  register_migrations:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install or update AWS CLI
        run: |
          if aws --version &> /dev/null; then
            echo "AWS CLI is already installed, using existing installation"
          else
            echo "Installing AWS CLI..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install UUID runtime
        run: sudo apt-get install -y uuid-runtime

      - name: Get changed SQL files
        id: changed-files
        run: |
          echo "Checking merged PR commit range..."
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"

          SQL_FILES=$(git fetch origin ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} && \
                     git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | \
                     grep '\.sql$' || echo "")

          echo "Found SQL files:"
          echo "$SQL_FILES"

          echo "SQL_FILES<<EOF" >> $GITHUB_ENV
          echo "$SQL_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Process migrations and write to DynamoDB
        run: |
          echo "$SQL_FILES" | while read -r file; do
            if [ -z "$file" ]; then
              continue
            fi
            filename=$(basename "$file" .sql)
            service=$(dirname "$file" | xargs basename)
            createdBy="${{ github.event.pull_request.user.login }}"
            createdAt=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            id=$(uuidgen)

            echo "Creating migration record for: $filename of service: $service"

            aws dynamodb put-item \
              --table-name migrations \
              --item "{
                \"id\": {\"S\": \"$id\"},
                \"name\": {\"S\": \"$filename\"},
                \"service\": {\"S\": \"$service\"},
                \"createdAt\": {\"S\": \"$createdAt\"},
                \"createdBy\": {\"S\": \"$createdBy\"},
                \"executedBy\": {\"NULL\": true}
              }"
          done
