name: Validate SQL Files

on:
  pull_request:
    paths:
      - "**.sql"

jobs:
  validate-sql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pgsanity
        run: |
          # Install PostgreSQL client tools (for ecpg needed by pgsanity)
          sudo apt-get update
          sudo apt-get install -y postgresql-client libecpg-dev

          # Install pgsanity
          pip install pgsanity
          echo "pgsanity installed successfully"

      - name: Validate SQL syntax
        id: syntax
        run: |
          error_log=""
          exit_code=0
          for file in $(find . -name "*.sql"); do
            echo "Validating syntax of $file..."
            output=$(pgsanity "$file" 2>&1) || {
              # Simplify error message and clean special characters
              cleaned_output=$(echo "$output" | tr '\n' ' ' | sed 's/"/'"'"'/g')
              error_log="${error_log}Error in ${file}: ${cleaned_output}. "
              
              # Extract line numbers and errors for GitHub annotations
              while IFS= read -r line; do
                if [[ $line =~ :[0-9]+: ]]; then
                  line_num=$(echo "$line" | grep -o ':[0-9]\+:' | tr -d ':')
                  error_msg=$(echo "$line" | sed "s/.*:[0-9]\+: //")
                  echo "::error file=${file},line=${line_num}::${error_msg}"
                fi
              done <<< "$output"
              
              exit_code=1
            }
          done

          if [ -n "$error_log" ]; then
            echo "error_log=${error_log}" >> $GITHUB_ENV
          fi

          exit ${exit_code}
        continue-on-error: true

      - name: Check for matching V/R files
        id: matching
        run: |
          error_log=""
          exit_code=0
          for vfile in $(find . -name "V*.sql"); do
            rfile="${vfile/V/R}"
            if [ ! -f "$rfile" ]; then
              error_log="${error_log}Missing rollback file for ${vfile}. "
              echo "::error file=${vfile}::Missing rollback file (${rfile})"
              exit_code=1
            fi
          done

          if [ -n "$error_log" ]; then
            echo "error_log_matching=${error_log}" >> $GITHUB_ENV
          fi

          exit ${exit_code}
        continue-on-error: true

      - name: Fail if any validation failed
        if: steps.syntax.outcome == 'failure' || steps.matching.outcome == 'failure'
        run: |
          echo "SQL validation failed!"
          if [ "${{ steps.syntax.outcome }}" == "failure" ]; then
            echo "Syntax errors:"
            echo "${{ env.error_log }}"
          fi
          if [ "${{ steps.matching.outcome }}" == "failure" ]; then
            echo "Missing rollback files:"
            echo "${{ env.error_log_matching }}"
          fi
          exit 1

      - name: Notify Slack on Failure
        uses: 8398a7/action-slack@v3
        if: failure()
        with:
          status: custom
          fields: ""
          custom_payload: |
            {
              "text": "🚫 *SQL validation failed*",
              "attachments": [{
                "color": "danger",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}",
                    "short": true
                  },
                  {
                    "title": "Pull Request",
                    "value": "<https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}|#${{ github.event.pull_request.number }}>",
                    "short": true
                  },
                  {
                    "title": "Workflow",
                    "value": "${{ github.workflow }}",
                    "short": true
                  },
                  {
                    "title": "Author",
                    "value": "@${{ github.event.pull_request.user.login }}",
                    "short": true
                  }
                ],
                "text": "*Error details:*\n${{ env.error_log }}${{ env.error_log_matching }}"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
