name: Validate Migration Dependencies

on:
  pull_request:
    paths:
      - "**.sql"

jobs:
  validate-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install networkx

      - name: Validate dependencies
        run: |
          python .github/scripts/validate_dependencies.py

      - name: Notify Slack on Failure
        uses: 8398a7/action-slack@v3
        if: failure()
        with:
          status: failure
          fields: repo,workflow,job,commit,message
          text: "Dependencies validation failed for ${{ github.event.pull_request.number }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
